version: "3.4"

x-app-service-template: &app
  build: rails_app
  image: yabeda-datadog-rails-app:1.0
  env_file:
    - rails.env
  volumes:
    - ./rails_app:/app

services:
  rails:
    <<: *app
    ports:
      - 5000:5000

  sidekiq:
    <<: *app
    ports:
      - 5100:5100
    environment:
      PORT: 5100
    command: sidekiq -C config/sidekiq.yml

  redis:
    image: redis
    command: redis-server

  datadog-agent:
    image: datadog/agent:latest
    env_file:
      - datadog-agent.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./datadog.yaml:/etc/datadog-agent/datadog.yaml
